name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy-scavgen:

    runs-on: ubuntu-latest

    steps:
    - name: Copy key
      run: |
        mkdir ~/.ssh
        echo ${{ secrets.BOT_KEY }} > ~/.ssh/scavgen_deploy_bot
        chmod 600 ~/.ssh/scavgen_deploy_bot
        ssh -i scavgen_deploy_bot ${{ secrets.BOT_NAME }}@${{ secrets.BOT_SERVER }} ${{ secrerts.DEPLOY_COMMAND }}
